<h1><?= $this->article->getTitle()?></h1>
<h4>Dans la catégorie <strong>
<?php 
$categorieArray[] = $this->article->getCategorie()->getNom(); 
$categorie = $this->article->getCategorie();
while($categorie->getParant() !== null) {
    $categorieArray[] = $categorie->getParant()->getNom();
    $categorie = $categorie->getParant();
}
$string = null;
foreach (array_reverse($categorieArray) as $cat) {
    $string .= $cat . ' >> ';
}
echo trim($string, ' >> ')
?>
</strong></h4>
<h4>Auteur :<?= $this->article->getAuteur()->getName();?></h4>
<p><?= $this->article->getContent()?></p>